# Generated by Django 3.2.10 on 2022-02-17 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Feedback Title')),
                ('feedback', models.CharField(max_length=1000, verbose_name='Feedback')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Feedback Deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Feedback Creation Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
