# Generated by Django 3.2.10 on 2022-02-15 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Url', '0002_url_is_deleted'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='url',
            index=models.Index(fields=['short_url'], name='short_url_idx'),
        ),
    ]
